### ISSUE TITLE
Automating three-finger drag on trackpad

### ISSUE THREAD

**Issue by jimratliff** [gerhard/setup#8]
This works for me (in El Capitan):
`echo "========= Implement three-finger dragging"
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerDragGesture -bool true
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true
`
Note, however, that I also include the following, which might help the above work (I'm not sure):
`# Disable one type of swipe between full-screen apps
echo "=========== Disable 3-finger horizontal swipe gesture"  
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerHorizSwipeGesture -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerHorizSwipeGesture -int 0
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 0

echo "=========== Disable 3-finger vertical swipe gesture"
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerVertSwipeGesture -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerVertSwipeGesture -int 0
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerVertSwipeGesture -int 0`

**Comment by gerhard** [comment]
Does this work the same in Mojave? #9 is not a laptop, so I ended up skipping this.

cc @argon
